### ISSUE TITLE
09/05 To-do list 

### ISSUE THREAD

**Issue by YunaJjo** [jsooshi/icu#11]
- [ ] [에이작스 로딩바 수정]
- [ ] [404 에러페이지]
- [ ] [헤더 프로필사진 세션에 저장]
- [ ] [이미지 캐러셀 크기고정]
- [ ] [카드 크기고정]
- [ ] [마이페이지 이미지 출력]
- [ ] [마이페이지 날짜 출력되는 형식변경]
- [ ] [헤더에 프로필이미지 띄우기]
- [ ] [프로필사진 수정기능]
- [ ] [댓글 페이징]
